name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/shadowhub/node-app  # Replace *** with shadowhub or confirm
  HELM_CHART_PATH: helm-charts/node-app
  TRIVY_SEVERITY: CRITICAL

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Install Docker Scout
        run: |
          # Install Docker Scout CLI
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin
          # Verify installation
          docker scout version

      - name: Analyze Image with Docker Scout
        run: |
          docker scout quickview ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Scan Image for CVEs with Docker Scout
        run: |
          docker scout cves ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Debug Image
        run: |
          echo "Image built: ${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }} || echo "Pull failed"

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-trivy-

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: table
          exit-code: 1
          severity: ${{ env.TRIVY_SEVERITY }}

      - name: Checkout Helm Charts Repo
        uses: actions/checkout@v4
        with:
          repository: chizchig/helm-charts
          token: ${{ secrets.PAT }}
          path: helm-charts

      - name: Debug Helm Charts Checkout
        run: |
          ls -la helm-charts
          ls -la ${{ env.HELM_CHART_PATH }} || echo "node-app directory not found"
          cat ${{ env.HELM_CHART_PATH }}/Chart.yml || echo "Chart.yml not found"
          cat ${{ env.HELM_CHART_PATH }}/values.yml || echo "values.yml not found"

      - name: Update Helm Chart
        run: |
          cd ${{ env.HELM_CHART_PATH }}
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yml || echo "  tag: ${{ github.sha }}" >> values.yml
          helm lint .
          cat values.yml  # Debug content

      - name: Commit Helm Chart Updates
        run: |
          cd helm-charts
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add node-app/values.yml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push || echo "Nothing to push (no changes)"